image: mcr.microsoft.com/playwright:focal

pipelines:
  default:
    - step:
        name: Run Playwright Tests
        caches:
          - node
        script:
          - npm install
          - npx playwright install --with-deps
          - HEADLESS=true npx playwright test