image: mcr.microsoft.com/playwright:focal

pipelines:
  default:
    - step:
        name: Run Playwright Tests
        caches:
          - node
        script:
          - npm install
          - npx playwright install --with-deps
          - HEADLESS=true npx playwright test
          - npx allure generate --single-file allure-results --clean -o static-allure-report
        artifacts:
          - static-allure-report/**