pipelines:
  branches:
    main:
      - step:
          name: Run Playwright Tests on Main
          caches:
            - node
            - playwright
          script:
            - npm ci
            - npx playwright install
            - npx playwright test
          artifacts:
            - playwright-report/**