image: mcr.microsoft.com/playwright:focal

pipelines:
  default:
    - step:
        name: Run Playwright Tests and Generate Allure Report
        caches:
          - node
        script:
          - apt-get update && apt-get install -y openjdk-11-jre-headless
          - npm install
          - npx playwright install --with-deps
          - HEADLESS=true npx playwright test
          - npx allure generate --single-file allure-results --clean -o static-allure-report
          - ls -l static-allure-report
          # Serve the report for 5 minutes (demo)
          - python3 -m http.server --directory static-allure-report 8080 &
          - echo "Serving report at http://localhost:8080 for 5 minutes"
          - sleep 300
        artifacts:
          - static-allure-report/*